crm/S2S_Auth_Blog/S2S_Auth_Blog/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OpenIdConnect;
using Microsoft.Owin.Security;

namespace S2S_Auth_Blog.Controllers
{
    public class AccountController : Controller
    {
        public void SignIn()
        {
            // Send an OpenID Connect sign-in request.
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = "/" },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

        public void SignOut()
        {
            string callbackUrl = Url.Action("SignOutCallback", "Account", routeValues: null, protocol: Request.Url.Scheme);

            HttpContext.GetOwinContext().Authentication.SignOut(
                new AuthenticationProperties { RedirectUri = callbackUrl },
                OpenIdConnectAuthenticationDefaults.AuthenticationType, CookieAuthenticationDefaults.AuthenticationType);
        }

        public ActionResult SignOutCallback()
        {
            if (Request.IsAuthenticated)
            {
                // Redirect to home page if the user is authenticated.
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

crm/S2S_Auth_Blog/S2S_Auth_Blog/Controllers/CrmController.cs
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.WebServiceClient;
using System;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using System.Configuration;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;
using System.Net.Http.Headers;
using System.Net.Http;

namespace S2S_Auth_Blog.Controllers
{
    public class CrmController : Controller
    {
        // Get App settings from Config file
        private string clientId = ConfigurationManager.AppSettings["ida:ClientId"];
        private string authority = ConfigurationManager.AppSettings["ida:AADInstance"] + "common";
        private string aadInstance = ConfigurationManager.AppSettings["ida:AADInstance"];
        private string OrganizationHostName = ConfigurationManager.AppSettings["ida:OrganizationHostName"];
        private string appKey = ConfigurationManager.AppSettings["ida:ClientSecret"];

        // GET: Crm
        [Authorize]
        public ActionResult Index()
        {
            string tenantID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;

            // Clean organization name from user logged
            string organizationName = User.Identity.Name.Substring(
             User.Identity.Name.IndexOf('@') + 1,
             User.Identity.Name.IndexOf('.') - (User.Identity.Name.IndexOf('@') + 1));

            //string crmResourceId = "https://[orgname].crm.microsoftonline.com";
            var resource = string.Format(OrganizationHostName, organizationName);

            // Request a token using application credentials
            ClientCredential clientcred = new ClientCredential(clientId, appKey);
            AuthenticationContext authenticationContext = new AuthenticationContext(aadInstance + tenantID);


            AuthenticationResult authenticationResult = authenticationContext.AcquireToken(resource, clientcred);
            var requestedToken = authenticationResult.AccessToken;

            // Invoke SDK using using the requested token
            using (var sdkService = new OrganizationWebProxyClient(GetServiceUrl(organizationName), false))
            {
                // Query CRM
                sdkService.HeaderToken = requestedToken;
                OrganizationRequest request = new OrganizationRequest()
                {
                    RequestName = "WhoAmI"
                };


                OrganizationResponse response = sdkService.Execute(request);

                return View((object)string.Join(",", response.Results.ToList()));
            }
        }

        private Uri GetServiceUrl(string organizationName)
        {
            var organizationUrl = new Uri(
             string.Format(OrganizationHostName, organizationName)
             );
            return new Uri(
             organizationUrl +
             @"/xrmservices/2011/organization.svc/web?SdkClientVersion=8.2"
         );
        }
    }
}

crm/S2S_Auth_Blog/S2S_Auth_Blog/Controllers/HomeController.cs
using System.Configuration;
using System.Security.Claims;
using System.ServiceModel.Description;
using System.Web.Mvc;

namespace S2S_Auth_Blog.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

crm/S2S_Auth_Blog/S2S_Auth_Blog/Views/Crm/Index.cshtml
@model string
@{
    ViewBag.Title = "CRM SDK WhoAmI";
}

<h2>@ViewBag.Title.</h2>

<p>Connected and executed sdk command.</p>

<p>Value: @Model</p>

crm/S2S_Auth_Blog/S2S_Auth_Blog/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

crm/S2S_Auth_Blog/S2S_Auth_Blog/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

crm/S2S_Auth_Blog/S2S_Auth_Blog/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

crm/S2S_Auth_Blog/S2S_Auth_Blog/Views/Home/LoadData.cshtml
@{
    ViewBag.Title = "LoadData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LoadData</h2>

crm/S2S_Auth_Blog/S2S_Auth_Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("WhoAmI", "Index", "Crm")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>